#Download base image ubuntu 22.04
FROM ubuntu:22.04

# System environments
ENV DEFAULT_ROOT="/var/www/html" \
    UID="1000" \
    GID="1000" \
    UNAME="developer" \
    TERM=xterm-256color \
    DEBIAN_FRONTEND=noninteractive

# Update Ubuntu Software repository
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -qq update && apt-get -yqq upgrade && \

# Install some basic tools needed for deployment
apt-get install -yqq apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed" && \
apt-get -yqq install --no-install-recommends \
    sudo \
    htop \
    tree \
    net-tools \
    iputils-ping \
    memcached \
    iproute2 \
    ca-certificates \
	build-essential \
	curl \
	wget \
	unzip \
	patch \
	rsync \
	vim \
	nano \
	openssh-client \
	openssh-server \
	mysql-client \
	git && \

# Install php8.1 + extensions
DEBIAN_FRONTEND=noninteractive apt-get -yqq install \
	php8.1 \
	php8.1-xml \
	php8.1-mbstring \
	php8.1-mysql \
	php8.1-curl \
	php8.1-cli \
	php8.1-gmp \
	php8.1-gd \
	php8.1-xdebug \
	libapache2-mod-php8.1 && \

# Install & configure apache2
apt-get install -yqq apache2 && \
sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf && \
sed -ri -e 's!/var/www/html!/var/www/html/src/web!g' /etc/apache2/sites-available/*.conf && \
a2enmod rewrite && \

# Install composer globally
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \

# Drush launcher
composer global require drush/drush && \
curl -OL https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar && \
mv drush.phar /usr/local/bin/drush && \
chmod +x /usr/local/bin/drush && \

# Create default developer user
groupadd $UNAME -g $GID; \
useradd -m -u $UID -g $GID -s /bin/bash -p $(perl -e 'print crypt($ARGV[0], "password")' 'developer') $UNAME; \
usermod -aG sudo $UNAME; \
usermod -aG www-data $UNAME;

EXPOSE 80 443 22 3306

