<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * @file
 * Contains the major_general.module file.
 */

function major_general_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_user = User::load(\Drupal::currentUser()->id());
  if (('user_form' == $form_id) 
    && !($current_user->hasRole('administrator') || $current_user->hasRole('request_manager'))) {
    unset($form['field_functional_areas']);
  }
}